export const meta = {
  name: "rollback",
  description: "Rolling back a turn restores the previous world, so a scenario can rewind without a fresh game.",
  aiCallBudget: 0,
};

export default async ({ game, world, expect, log }) => {
  const before = await world.snapshot();
  log.info(`starting at round ${before.round}, ${before.gameDate}`);

  const turn = log.turn(await game.turn(30));
  expect.roundAdvanced(turn.diff);

  const snapshots = await game.snapshots();
  expect.that(
    Array.isArray(snapshots) && snapshots.length > 0,
    "a turn should capture a rollback snapshot",
    { count: Array.isArray(snapshots) ? snapshots.length : null },
  );
  if (!Array.isArray(snapshots) || !snapshots.length) return;

  const restored = await game.rollback(0);
  expect.that(restored.ok, "rolling back should not throw", { error: restored.error?.message });

  const after = await world.snapshot();
  expect.equal(after.round, before.round, "the round should be back where it started");
  expect.equal(after.gameDate, before.gameDate, "and so should the date");
  expect.equal(
    after.counts.events,
    before.counts.events,
    "the events generated by the rolled-back turn should be gone",
  );
};
