// Assertions that COLLECT rather than throw on the first failure.
//
// A scenario that stops at its first bad assertion tells me one thing per run,
// and each run costs a real turn. Collecting means one run reports every problem
// it found, which is the difference between "Bavaria did not transfer" and
// "Bavaria did not transfer, the 3rd Army never moved, and the turn silently fell
// back to canned events".

const asArray = (value) => (Array.isArray(value) ? value : []);

export const createExpect = ({ journal = null } = {}) => {
  const results = [];

  const record = (ok, message, detail = null) => {
    results.push({ ok, message, detail });
    journal?.assertion({ ok, message, detail });
    return ok;
  };

  const expect = {
    get results() {
      return [...results];
    },
    get passed() {
      return results.filter((r) => r.ok).length;
    },
    get failed() {
      return results.filter((r) => !r.ok).length;
    },
    get failures() {
      return results.filter((r) => !r.ok);
    },

    ok: (value, message) => record(Boolean(value), message ?? "expected a truthy value", { value }),

    equal: (actual, expected, message) =>
      record(
        Object.is(actual, expected),
        message ?? `expected ${JSON.stringify(expected)}`,
        { actual, expected },
      ),

    /** The region assertion. Accepts an id or a name via the diff's own resolver. */
    regionOwner: (snapshot, regionIdOrName, expected, message) => {
      const id = Object.keys(snapshot.ownership ?? {}).includes(regionIdOrName)
        ? regionIdOrName
        : Object.entries(snapshot.ownership ?? {}).find(([key]) => key === regionIdOrName)?.[0];
      const actual = id ? snapshot.ownership[id] : undefined;
      return record(
        actual === expected,
        message ?? `${regionIdOrName} should belong to ${expected}`,
        { regionId: id ?? regionIdOrName, actual: actual ?? null, expected },
      );
    },

    transferred: (diff, { region, from, to }, message) => {
      const match = diff.regions.transferred.find(
        (entry) => entry.id === region || entry.name === region,
      );
      const ok = Boolean(match) && (!from || match.from === from) && (!to || match.to === to);
      return record(
        ok,
        message ?? `${region} should have transferred${to ? ` to ${to}` : ""}`,
        { found: match ?? null, transferred: diff.regions.transferred },
      );
    },

    notTransferred: (diff, region, message) =>
      record(
        !diff.regions.transferred.some((entry) => entry.id === region || entry.name === region),
        message ?? `${region} should NOT have changed hands`,
        { transferred: diff.regions.transferred },
      ),

    unitCount: (snapshot, expected, message) =>
      record(
        snapshot.counts.units === expected,
        message ?? `expected ${expected} units`,
        { actual: snapshot.counts.units, expected },
      ),

    unitMoved: (diff, nameOrId, message) =>
      record(
        diff.units.moved.some((unit) => unit.id === nameOrId || unit.name === nameOrId),
        message ?? `${nameOrId} should have moved`,
        { moved: diff.units.moved },
      ),

    eventMatching: (diff, pattern, message) => {
      const re = pattern instanceof RegExp ? pattern : new RegExp(String(pattern), "i");
      return record(
        diff.events.added.some((event) => re.test(event.title ?? "")),
        message ?? `an event matching ${re} should have been generated`,
        { titles: diff.events.added.map((e) => e.title) },
      );
    },

    roundAdvanced: (diff, message) =>
      record(
        Array.isArray(diff.game.round) && diff.game.round[1] > diff.game.round[0],
        message ?? "the round should have advanced",
        { round: diff.game.round },
      ),

    dateAdvanced: (diff, message) =>
      record(
        Array.isArray(diff.game.gameDate) && diff.game.gameDate[1] > diff.game.gameDate[0],
        message ?? "the game date should have advanced",
        { gameDate: diff.game.gameDate },
      ),

    /**
     * The most important assertion in an AI run.
     *
     * A fallback turn looks like a success from the outside: the round advances,
     * events appear, state persists. Only `generation.source` distinguishes "the
     * model answered" from "the model never answered and the engine improvised".
     */
    generatedByAi: (outcome, message) =>
      record(
        outcome?.generation?.source === "ai",
        message ?? "the turn should have been generated by the model, not the fallback",
        { generation: outcome?.generation ?? null, fallbackReason: outcome?.fallback ?? null },
      ),

    noFallback: (outcome, message) =>
      record(!outcome?.fallback, message ?? "the turn should not have fallen back", {
        fallbackReason: outcome?.fallback ?? null,
      }),

    /** Every territorial claim the AI made actually landed on the map. */
    noUnappliedTransfers: (diff, message) =>
      record(
        asArray(diff.reconciliation?.transfers?.unapplied).length === 0,
        message ?? "every claimed region transfer should have been applied",
        { unapplied: diff.reconciliation?.transfers?.unapplied ?? [] },
      ),

    mapTruthAtLeast: (diff, threshold, message) => {
      const score = diff.reconciliation?.mapTruthScore;
      return record(
        score === null || score >= threshold,
        message ?? `map truth should be at least ${threshold}`,
        { score, threshold, unapplied: diff.reconciliation?.transfers?.unapplied ?? [] },
      );
    },

    aiCalls: (outcome, { atMost = Infinity, atLeast = 0 } = {}, message) => {
      const calls = outcome?.providerCalls ?? 0;
      return record(
        calls <= atMost && calls >= atLeast,
        message ?? `expected between ${atLeast} and ${atMost} provider calls, got ${calls}`,
        { calls, atMost, atLeast },
      );
    },

    within: (outcome, ms, message) =>
      record(outcome.ms <= ms, message ?? `should complete within ${ms}ms`, { ms: outcome.ms }),

    /** Escape hatch for a one-off condition that has no verb yet. */
    that: (ok, message, detail) => record(Boolean(ok), message, detail),
  };

  return expect;
};
